@extends('layouts.layout')

@section('content')
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Sensor Report</h1>
        </div>

        <section class="section dashboard">
            <div class="container mt-4">
                @if (in_array('create', $global_permissions['report_access'] ?? []) ||
                        in_array('full', $global_permissions['report_access'] ?? []))
                    <div class="card shadow-lg border-0 rounded-4 p-3">
                        <div class="card-body">
                            <h5 class="card-title">Generate New Report</h5>
                            <form action="{{ route('report.store') }}" method="POST">
                                @csrf
                                <div class="d-flex align-items-center gap-3 mb-3">
                                    <label class="form-label w-25">Substation</label>
                                    <select name="report_substation" class="form-control w-75">
                                        <option value=""></option>
                                        @foreach ($substations as $substation)
                                            <option value="{{ $substation->id }}">{{ $substation->substation_name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="d-flex align-items-center gap-3 mb-3">
                                    <label class="form-label w-25">Start Date</label>
                                    <input name="start_date" type="date" class="form-control w-75">
                                </div>
                                <div class="d-flex align-items-center gap-3 mb-3">
                                    <label class="form-label w-25">End Date</label>
                                    <input name="end_date" type="date" class="form-control w-75">
                                </div>

                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary px-4">Generate</button>
                                </div>

                            </form>
                            {{-- @endcan --}}
                        </div>
                    </div>
                @endif

                <div class="card shadow-lg p-4">
                    <h5 class="card-title">Generated Reports</h5>
                    <table class="table table-bordered align-middle text-center">
                        <thead class="table-light">
                            <tr>
                                <th>#</th>
                                <th>Substation</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Generated By</th>
                                <th>Download</th>
                                @if (in_array('delete', $global_permissions['report_access'] ?? []) ||
                                        in_array('full', $global_permissions['report_access'] ?? []))
                                    <th>Action</th>
                                @endif
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($reports as $report)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $report->substation->substation_name }}</td>
                                    <td>{{ $report->start_date }}</td>
                                    <td>{{ $report->end_date }}</td>
                                    <td>{{ $report->user->name }}</td>
                                    <td>
                                        <a href="{{ route('report.download', $report->id) }}"
                                            class="text-success bi bi-download"></a>
                                    </td>
                                    @if (in_array('delete', $global_permissions['report_access'] ?? []) ||
                                            in_array('full', $global_permissions['report_access'] ?? []))
                                        <td>
                                            <form action="{{ route('report.destroy', $report->id) }}" method="POST"
                                                onsubmit="return confirm('Are you sure you want to delete this report?');"
                                                style="display: inline;">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                    class="border-0 bg-transparent text-danger bi bi-trash"></button>
                                            </form>
                                        </td>
                                    @endif
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </section>
    </main>
@endsection
