<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Substation Report - {{ $substation->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; line-height: 1.6; color: #333; }
        h2, h3 { border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        ul { margin: 0; padding-left: 20px; }
        .section { margin-bottom: 30px; }
        .nested-ul { margin-top: 5px; padding-left: 20px; }
        .meta { font-size: 0.9em; color: #666; }
    </style>
</head>
<body>

    <h2>Substation Report</h2>
    <p><strong>Substation:</strong> {{ $substation->name }}</p>
    <p class="meta">Report Period: {{ $start_date }} to {{ $end_date }}</p>
    <p class="meta">Generated by: {{ $generated_by }} on {{ \Carbon\Carbon::parse($generated_at)->format('d M Y, H:i') }}</p>

    <div class="section">
        <h3>1. Temperature Sensor Summary</h3>
        <ul>
            <li><strong>Average Red Phase:</strong> {{ $tempStats['average_red'] }} °C</li>
            <li><strong>Average Yellow Phase:</strong> {{ $tempStats['average_yellow'] }} °C</li>
            <li><strong>Average Blue Phase:</strong> {{ $tempStats['average_blue'] }} °C</li>
            <li><strong>Maximum Temperature:</strong> {{ $tempStats['max_temp'] }} °C</li>
            <li><strong>Minimum Temperature:</strong> {{ $tempStats['min_temp'] }} °C</li>
            <li><strong>Average Variance:</strong> {{ $tempStats['variance_avg'] }} %</li>
            <li><strong>Alerts:</strong>
                @if($tempStats['alerts']->isEmpty())
                    None
                @else
                    @foreach($tempStats['alerts'] as $level => $count)
                        {{ ucfirst($level) }} ({{ $count }}){{ !$loop->last ? ',' : '' }}
                    @endforeach
                @endif
            </li>
        </ul>
    </div>

    <div class="section">
        <h3>2. Partial Discharge Summary</h3>
        <ul>
            <li><strong>Average Mean Ratio:</strong> {{ $pdStats['avg_mean_ratio'] }}</li>
            <li><strong>Average Indicator:</strong> {{ $pdStats['avg_indicator'] }}</li>
            <li><strong>Alerts:</strong>
                @if($pdStats['alerts']->isEmpty())
                    None
                @else
                    @foreach($pdStats['alerts'] as $level => $count)
                        {{ ucfirst($level) }} ({{ $count }}){{ !$loop->last ? ',' : '' }}
                    @endforeach
                @endif
            </li>
        </ul>
    </div>

    <div class="section">
        <h3>3. Error Log Summary</h3>
        <ul>
            <li><strong>Total Errors:</strong> {{ $errorStats['total'] }}</li>
    
            @if($errorStats['total'] > 0)
                <li><strong>By State:</strong>
                    <ul class="nested-ul">
                        @foreach($errorStats['by_state'] as $state => $count)
                            <li>{{ $state }}: {{ $count }}</li>
                        @endforeach
                    </ul>
                </li>
    
                <li><strong>By Severity:</strong>
                    <ul class="nested-ul">
                        @foreach($errorStats['by_severity'] as $severity => $count)
                            <li>{{ $severity }}: {{ $count }}</li>
                        @endforeach
                    </ul>
                </li>
            @endif
        </ul>
    </div>    

</body>
</html>
