<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Substation Report - {{ $substation->name }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }

        h2 {
            font-size: 24px;
            margin-bottom: 10px;
            border-bottom: 2px solid #555;
            padding-bottom: 5px;
        }

        h3 {
            font-size: 20px;
            margin-top: 40px;
            margin-bottom: 10px;
            border-bottom: 1px solid #999;
            padding-bottom: 4px;
        }

        h4 {
            font-size: 16px;
            margin-top: 20px;
            margin-bottom: 8px;
            font-weight: bold;
        }

        .meta {
            font-size: 0.9em;
            color: #666;
        }

        .section {
            margin-top: 30px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
            font-size: 0.95em;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 8px 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        ul {
            margin: 0;
            padding-left: 20px;
        }

        .nested-ul {
            padding-left: 20px;
            margin-top: 5px;
        }

        .subsection {
            margin-top: 15px;
        }

        .highlight {
            font-weight: bold;
        }
    </style>
</head>

<body>

    <h2>Substation Report: {{ $substation->substation_name }}</h2>
    <p class="meta">Report Period: {{ $start_date }} to {{ $end_date }}</p>
    <p class="meta">Generated by: {{ $generated_by }} on {{ \Carbon\Carbon::parse($generated_at)->format('d M Y, H:i') }}</p>

    <div class="section">
        <h3>1. Temperature Sensor Summary</h3>
        <table>
            <thead>
                <tr>
                    <th>Sensor ID</th>
                    <th>Sensor Name</th>
                    <th>Max Diff Temp (°C)</th>
                    <th>Recorded At</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($maxDiffTempPerSensor as $sensorData)
                    <tr>
                        <td>{{ $sensorData['sensor_id'] }}</td>
                        <td>{{ $sensorData['sensor_name'] }}</td>
                        <td>{{ $sensorData['max_diff_temp'] }}</td>
                        <td>{{ $sensorData['recorded_at'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h3>2. Partial Discharge Summary</h3>
        <table>
            <thead>
                <tr>
                    <th>Sensor ID</th>
                    <th>Sensor Name</th>
                    <th>Max Indicator</th>
                    <th>Recorded At</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($maxIndPerSensor as $sensorData)
                    <tr>
                        <td>{{ $sensorData['sensor_id'] }}</td>
                        <td>{{ $sensorData['sensor_name'] }}</td>
                        <td>{{ $sensorData['max_indicator'] }}</td>
                        <td>{{ $sensorData['recorded_at'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h3>3. Error Log Summary</h3>

        <div class="subsection">
            <h4>3.1 Overall Statistics</h4>
            <ul>
                <li><span class="highlight">Total Errors:</span> {{ $errorStats->sum('error_count') }}</li>
                <li><span class="highlight">Sensors with Errors:</span> {{ $errorStats->count() }}</li>

                @if ($errorStats->count() > 0)
                    @php
                        $allSeverities = $errorStats->pluck('severity_levels')->flatten()->countBy();
                        $allStates = $errorStats->pluck('states')->flatten()->countBy();
                        $allStatuses = $errorStats->pluck('status_breakdown')->collapse();
                        $sensorTypes = $errorStats->groupBy('sensor_type')->map->count();
                    @endphp

                    <li><span class="highlight">By Severity:</span>
                        <ul class="nested-ul">
                            @foreach ($allSeverities as $severity => $count)
                                <li>{{ $severity }}: {{ $count }}</li>
                            @endforeach
                        </ul>
                    </li>

                    <li><span class="highlight">By Status:</span>
                        <ul class="nested-ul">
                            @foreach ($allStatuses as $status => $count)
                                <li>{{ $status }}: {{ $count }}</li>
                            @endforeach
                        </ul>
                    </li>

                    <li><span class="highlight">By State:</span>
                        <ul class="nested-ul">
                            @foreach ($allStates as $state => $count)
                                <li>{{ $state }}: {{ $count }}</li>
                            @endforeach
                        </ul>
                    </li>

                    <li><span class="highlight">By Sensor Type:</span>
                        <ul class="nested-ul">
                            @foreach ($sensorTypes as $type => $count)
                                <li>{{ class_basename($type) }}: {{ $count }}</li>
                            @endforeach
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>

</body>

</html>
